### PR TITLE
Added javascript file

### PR DESCRIPTION
**Pull request by Tumisang9x**
Chatbot 

<p> Chatbot javascript code is added here </p>

### CODE REVIEW

**Comment by Tumisang9x** [comment]
can you guys see my comment?

**Review by NompiloZondo-Dev — APPROVED** [review]
ok noted

**Review by NkosinathiSeptember23 — COMMENTED** [review]
Everything is fine you can merge

**Review by desreedimaky — APPROVED** [review]

**Comment by KevinM55** [comment]
Add more dialogue content between the bot and the user

**Comment by KevinM55** [comment]
Please fix your selection choice so we do not have to greet the bot everytime we need it to appear

**Review by KevinM55 — APPROVED** [review]

**Pull request merged**
